<?php

namespace Entity\Repository;

/**
 * OrdersheetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersheetRepository extends \Doctrine\ORM\EntityRepository
{
}
