<?php

namespace Entity\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * 统计要插入的新id
     * @return string
     */
    public function getnewID()
    {
        return $this->_em->createQueryBuilder()
                         ->select("max(p.productId)+1 as new_pid")
                         ->from('Entity\Product','p')
                         ->getQuery()->getSingleScalarResult();
    }
    
}
